### ISSUE TITLE
Phase 01 Tasks

### ISSUE THREAD

**Issue by MoeeinAali** [MoeeinAali/DB-Project#1]
## Todo-List
- [x] Create a GitHub repository and define the issue
- [x] Identify entities from the project document
- [x] Identify attributes from the project document
- [x] Draw entities and attributes in Draw.io
- [x] Draw relationships in Draw.io
- [x] Prepare LaTeX for project answers
- [x] Write relational algebra
- [x] Write relational algebra in LaTeX
- [x] Write explanations for the ERD

<details>
  <summary>Person 1: Melika Alizadeh</summary>

  - [x] Identify entities from the project document
  - [x] Identify attributes from the project document
  - [x] Draw entities and attributes in Draw.io
  - [x] Draw relationships in Draw.io
  - [x] Write explanations for the ERD
</details>

<details>
  <summary>Person 2: Samin Akbari</summary>

- [x] Identify entities from the project document
- [x] Identify attributes from the project document
- [x] Draw entities and attributes in Draw.io
- [x] Draw relationships in Draw.io
- [x] Write explanations for the ERD
</details>

<details>
  <summary>Person 3: Moeein Aali</summary>

- [x] Create a GitHub repository and define the issue
- [x] Draw entities and attributes in Draw.io
- [x] Prepare LaTeX for project answers
- [x] Write relational algebra
- [x] Write relational algebra in LaTeX
</details>
